name: 🍳Test call a reusable workflow and use its outputs ✈
run-name: Test call a reusable workflow and use its outputs
on: [push]

jobs:
  job1:
    name: Reuse workflow
    uses: ./.github/workflows/c-test-reusable-output-workflow.yml

  job2:
    name: Output message
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}