name: Publish release event demo
run-name: 03-${{ github.actor }} publish release version on ${{github.ref}}

on: 
  release:
    types: [published]

jobs:

  Check-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checking version ${{github.ref_name}} if matching
        uses: actions-ecosystem/action-regex-match@v2
        id: match-rel-version
        with:
          text: ${{ github.ref_name }}
          regex: '^v?[0-9]+(\.[0-9]+){0,2}(-[a-zA-Z]+[0-9]*)?$'
      - name: Deploy Release version ${{github.ref_name}}
        if: ${{ !github.event.release.prerelease && steps.match-rel-version.outputs.match != '' }}
        run: echo "--->Release..."
      - name: Deploy Snapshot version ${{github.ref_name}}
        if: ${{ !(!github.event.release.prerelease && steps.match-rel-version.outputs.match != '') }}
        run: echo "#### Snapshot..."

  check_if_release_version:
    name: Check if release with version ${{github.ref_name}} and prelease flag ${{github.event.release.prerelease}}
    runs-on: ubuntu-latest
    outputs:
      matched: ${{ steps.check-rel-flag.outputs.matched }}   
    steps:
      - name: Checking version ${{github.ref_name}} if matching
        uses: actions-ecosystem/action-regex-match@v2
        id: match-rel-version
        with:
          text: ${{ github.ref_name }}
          regex: '^v?[0-9]+(\.[0-9]+){0,2}(-[a-zA-Z]+[0-9]*)?$'
      #
      - id: check-rel-flag
        name: Check Release flag
        run: |
          if [[ !${{github.event.release.prerelease}} && "${{steps.match-rel-version.outputs.match}}" != "" ]]; then
            echo "matched=true" >> $GITHUB_OUTPUT
            echo "### Release ###"
          else
            echo "matched=false" >> $GITHUB_OUTPUT 
            echo ">>>Not release<<<"
          fi
          cat $GITHUB_OUTPUT

  deploy_to_external_repository:
    name: 🎉Release version will be deployed to external repository🚀
    runs-on: ubuntu-latest
    needs: check_if_release_version
    if: ${{ needs.check_if_release_version.outputs.matched == 'true' }}
    steps:
        - run: echo "Publish to external with version with release versoin"

  deploy_to_internal_repository:
    runs-on: ubuntu-latest
    needs: check_if_release_version
    name: 🎬Snapshot version will be deployed to internal repository⏰
    if: ${{ needs.check_if_release_version.outputs.matched == 'false' }}
    steps:
        - run: echo "Publish to internal with snapshot version "
      
     
