name: Print github context list
# run-name: ${{ github.actor }} is print github context list on ${{github.ref}} on release

on: 
  # [release]
  release:
    types: [published]

jobs:

  Check-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checking version ${{github.ref_name}} if matching
        uses: actions-ecosystem/action-regex-match@v2
        id: match-rel-version
        with:
          text: ${{ github.ref_name }}
          regex: '^v?[0-9]+(\.[0-9]+){0,2}(-[a-zA-Z]+[0-9]*)?$'
      - name: Deploy Release version ${{github.ref_name}}
        if: ${{ !github.event.release.prerelease && steps.match-rel-version.outputs.match != '' }}
        run: echo "--->Release..."
      - name: Deploy Snapshot version ${{github.ref_name}}
        if: ${{ !(!github.event.release.prerelease && steps.match-rel-version.outputs.match != '') }}
        run: echo "#### Snapshot..."

  # Release-Version:
  #   if: ${{ github.event.release.prerelease && github.ref_name =~ ^v?[0-9]+(\.[0-9]+){0,2}(-[a-zA-Z]+[0-9]*)?$ }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo ">>>>> Releasing....."

  # Snapshot-Version:
  #   if: ${{ !(github.event.release.prerelease && github.ref_name =~ ^v?[0-9]+(\.[0-9]+){0,2}(-[a-zA-Z]+[0-9]*)?$) }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo ">>>>> Releasing....."
     
