name: 🍕View event json
on: [push]

jobs:
    print_context:
      name: ${{github.actor}} shows event json
      runs-on: ubuntu-latest
      steps:
        - env:
            EVENT_CONTEXT: ${{ toJSON(github.event) }}
          run: |
            echo $EVENT_CONTEXT